# NumPy Übung - Aufgabe

Jetzt wo wir schon einiges über NumPy gelernt haben können wir unser Wissen überprüfen. Wir starten dazu mit einigen einfachen Aufgaben und steigern uns zu komplizierteren Fragestellungen.

**Importiere NumPy als np**

In [1]:
import numpy as np

**Erstelle ein Array von 10 Nullen**

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Erstelle ein Array von 10 Einsen**

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

**Erstelle ein Array von 10 Fünfen**

In [7]:
np.array(10*[5])

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

**Erstelle ein Array der Zahlen von 10 bis 50**

In [14]:
np.arange(10, 51, 1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

**Erstelle ein Array aller gerader Zahlen zwischen 10 und 50**

In [15]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

**Erstelle eine 3x3 Matrix, die die Zahlen von 0 bis 8 beinhaltet**

In [16]:
np.reshape(np.arange(0, 9), (3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**Erstelle eine 3x3 Einheitsmatrix**

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Nutze NumPy, um eine Zufallszahl zwischen 0 und 1 zu erstellen**

In [18]:
np.random.rand(1)

array([0.06037542])

**Nutze NumPy, um ein Array von 25 Zufallszahlen, die einer Standardnormalverteilung folgen, zu erstellen**

In [20]:
np.random.randn(25)

array([-0.06276364,  1.45078883, -0.41098935,  1.18226113, -1.37469427,
       -2.33093132,  0.45043724,  1.17238179,  0.45070922,  0.83317422,
       -0.46749657, -0.48678883,  0.23398715, -0.98334383, -2.36203568,
        0.07494253, -0.71291676, -0.05565342, -0.40783954,  0.79094563,
       -0.64829104,  0.29755179,  1.05471974, -0.38613756, -1.0684665 ])

**Erstelle die folgende Matrix:**

In [26]:
np.arange(0.01, 1.01, 0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

**Erstelle ein Array aus 20 gleichmäßig verteilten Punkten zwischen 0 und 1**

In [27]:
np.random.rand(20)

array([0.14350072, 0.31905088, 0.46737966, 0.701722  , 0.12584488,
       0.03160845, 0.5320157 , 0.05849772, 0.23742691, 0.83633946,
       0.81627346, 0.55855049, 0.14777561, 0.20604964, 0.54003957,
       0.11758459, 0.53701035, 0.0853974 , 0.7601538 , 0.80205253])

## NumPy Indexing und Selection

Du wirst nun einige Matrizen sehen und deine Aufgabe ist es, die angezeigten Ergebnis-Outputs zu reproduzieren:

In [28]:
m = np.arange(1, 26).reshape(5,5)
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [15]:
# Schreibe deinen Code hier, der das Ergebnis reproduzieren soll
# Achte darauf, die untere Zelle nicht auszuführen, sonst
# wirst du das Ergebnis nicht mehr sehen können

In [29]:
m[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [17]:
# Schreibe deinen Code hier, der das Ergebnis reproduzieren soll
# Achte darauf, die untere Zelle nicht auszuführen, sonst
# wirst du das Ergebnis nicht mehr sehen können

In [30]:
m[3][4]

20

In [20]:
# Schreibe deinen Code hier, der das Ergebnis reproduzieren soll
# Achte darauf, die untere Zelle nicht auszuführen, sonst
# wirst du das Ergebnis nicht mehr sehen können

In [36]:
m[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [22]:
# Schreibe deinen Code hier, der das Ergebnis reproduzieren soll
# Achte darauf, die untere Zelle nicht auszuführen, sonst
# wirst du das Ergebnis nicht mehr sehen können

In [37]:
m[[4]]

array([[21, 22, 23, 24, 25]])

In [23]:
# Schreibe deinen Code hier, der das Ergebnis reproduzieren soll
# Achte darauf, die untere Zelle nicht auszuführen, sonst
# wirst du das Ergebnis nicht mehr sehen können

In [38]:
m[[3,4]]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Mache jetzt folgendes

**Erzeuge die Summe aller Werte in der Matrix**

In [39]:
m.sum()

325

**Erhalte die Standardabweichung der Werte in der Matrix**

In [40]:
m.std()

7.211102550927978

**Erhalte die Summe aller Spalten in der Matrix**

In [42]:
m.sum(axis=0)

array([55, 60, 65, 70, 75])

# Gut gemacht!